<a href="https://colab.research.google.com/github/jagtapswati/data-science-/blob/main/day2pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

In [ ]:
upload=files.upload()

Saving imdbtop.csv to imdbtop.csv

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("imdbtop.csv")

In [ ]:
df

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [ ]:
df.shape

(1000, 16)

In [ ]:
df.tail()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [ ]:
df.isna().sum()

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,https://m.media-amazon.com/images/M/MV5BYjRmY2...,Giù la testa,1971,PG,157 min,"Drama, War, Western",7.6,A low-life bandit and an I.R.A. explosives exp...,77.0,Sergio Leone,Rod Steiger,James Coburn,Romolo Valli,Maria Monti,30144,"696,690"
991,https://m.media-amazon.com/images/M/MV5BMzAyND...,Kelly's Heroes,1970,GP,144 min,"Adventure, Comedy, War",7.6,A group of U.S. soldiers sneaks across enemy l...,50.0,Brian G. Hutton,Clint Eastwood,Telly Savalas,Don Rickles,Carroll O'Connor,45338,"1,378,435"
992,https://m.media-amazon.com/images/M/MV5BMjAwMT...,The Jungle Book,1967,U,78 min,"Animation, Adventure, Family",7.6,Bagheera the Panther and Baloo the Bear have a...,65.0,Wolfgang Reitherman,Phil Harris,Sebastian Cabot,Louis Prima,Bruce Reitherman,166409,"141,843,612"
994,https://m.media-amazon.com/images/M/MV5BZjQyMG...,A Hard Day's Night,1964,U,87 min,"Comedy, Music, Musical",7.6,"Over two ""typical"" days in the life of The Bea...",96.0,Richard Lester,John Lennon,Paul McCartney,George Harrison,Ringo Starr,40351,"13,780,024"
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"

In [ ]:
df['Genre'].value_counts()

Drama                         58
Drama, Romance                26
Comedy, Drama                 24
Crime, Drama, Thriller        22
Action, Adventure, Sci-Fi     21
                              ..
Crime, Film-Noir, Thriller     1
Drama, Film-Noir, Romance      1
Drama, History, Romance        1
Adventure, Horror, Sci-Fi      1
Comedy, Music, Musical         1
Name: Genre, Length: 172, dtype: int64

In [ ]:
df['Certificate'].value_counts()

U           183
A           174
UA          142
R           131
PG-13        38
PG           19
G             9
Passed        9
Approved      6
TV-PG         1
U/A           1
GP            1
Name: Certificate, dtype: int64

In [ ]:
df.describe()

       IMDB_Rating  Meta_score   No_of_Votes
count   714.000000  714.000000  7.140000e+02
mean      7.937115   77.158263  3.561348e+05
std       0.293278   12.401144  3.539011e+05
min       7.600000   28.000000  2.522900e+04
25%       7.700000   70.000000  9.600975e+04
50%       7.900000   78.000000  2.366025e+05
75%       8.100000   86.000000  5.077922e+05
max       9.300000  100.000000  2.343110e+06

In [ ]:
filt=df['Genre'].str.contains('Romance',na=False)

In [ ]:
filt.value_counts()

False    626
True      88
Name: Genre, dtype: int64

In [ ]:
df.loc[filt]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
11,https://m.media-amazon.com/images/M/MV5BNWIwOD...,Forrest Gump,1994,UA,142 min,"Drama, Romance",8.8,"The presidencies of Kennedy and Johnson, the e...",82.0,Robert Zemeckis,Tom Hanks,Robin Wright,Gary Sinise,Sally Field,1809221,"330,252,182"
26,https://m.media-amazon.com/images/M/MV5BYmJmM2...,La vita è bella,1997,U,116 min,"Comedy, Drama, Romance",8.6,When an open-minded Jewish librarian and his s...,59.0,Roberto Benigni,Roberto Benigni,Nicoletta Braschi,Giorgio Cantarini,Giustino Durano,623629,"57,598,247"
45,https://m.media-amazon.com/images/M/MV5BM2FhYj...,Nuovo Cinema Paradiso,1988,U,155 min,"Drama, Romance",8.5,A filmmaker recalls his childhood when falling...,80.0,Giuseppe Tornatore,Philippe Noiret,Enzo Cannavale,Antonella Attili,Isa Danieli,230763,"11,990,401"
50,https://m.media-amazon.com/images/M/MV5BY2IzZG...,Casablanca,1942,U,102 min,"Drama, Romance, War",8.5,A cynical expatriate American cafe owner strug...,100.0,Michael Curtiz,Humphrey Bogart,Ingrid Bergman,Paul Henreid,Claude Rains,522093,"1,024,560"
52,https://m.media-amazon.com/images/M/MV5BY2I4Mm...,City Lights,1931,G,87 min,"Comedy, Drama, Romance",8.5,"With the aid of a wealthy erratic tippler, a d...",99.0,Charles Chaplin,Charles Chaplin,Virginia Cherrill,Florence Lee,Harry Myers,167839,"19,181"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965,https://m.media-amazon.com/images/M/MV5BNmRiZD...,The Bridges of Madison County,1995,A,135 min,"Drama, Romance",7.6,Photographer Robert Kincaid wanders into the l...,69.0,Clint Eastwood,Clint Eastwood,Meryl Streep,Annie Corley,Victor Slezak,73172,"71,516,617"
967,https://m.media-amazon.com/images/M/MV5BNTliYT...,Trois couleurs: Blanc,1994,U,92 min,"Comedy, Drama, Romance",7.6,"After his wife divorces him, a Polish immigran...",88.0,Krzysztof Kieslowski,Zbigniew Zamachowski,Julie Delpy,Janusz Gajos,Jerzy Stuhr,64390,"1,464,625"
971,https://m.media-amazon.com/images/M/MV5BMTY5Nj...,Omohide poro poro,1991,U,118 min,"Animation, Drama, Romance",7.6,A twenty-seven-year-old office worker travels ...,90.0,Isao Takahata,Miki Imai,Toshirô Yanagiba,Yoko Honna,Mayumi Izuka,27071,"453,243"
975,https://m.media-amazon.com/images/M/MV5BMjE0OD...,When Harry Met Sally...,1989,UA,95 min,"Comedy, Drama, Romance",7.6,Harry and Sally have known each other for year...,76.0,Rob Reiner,Billy Crystal,Meg Ryan,Carrie Fisher,Bruno Kirby,195663,"92,823,600"
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"

In [ ]:
df['Runtime']

0      142 min
1      175 min
2      152 min
3      202 min
4       96 min
        ...
990    157 min
991    144 min
992     78 min
994     87 min
997    118 min
Name: Runtime, Length: 714, dtype: object

In [ ]:
df['Runtime']=df['Runtime'].apply(lambda x: x.split(" "))

In [ ]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,"[142, min]",Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,"[175, min]","Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,"[152, min]","Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,"[202, min]","Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,"[96, min]","Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [ ]:
df['Runtime']=df['Runtime'].apply(lambda x: x[0])

In [ ]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 997
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    714 non-null    object
 1   Series_Title   714 non-null    object
 2   Released_Year  714 non-null    object
 3   Certificate    714 non-null    object
 4   Runtime        714 non-null    object
 5   Genre          714 non-null    object
 6   IMDB_Rating    714 non-null    float64
 7   Overview       714 non-null    object
 8   Meta_score     714 non-null    float64
 9   Director       714 non-null    object
 10  Star1          714 non-null    object
 11  Star2          714 non-null    object
 12  Star3          714 non-null    object
 13  Star4          714 non-null    object
 14  No_of_Votes    714 non-null    int64
 15  Gross          714 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 94.8+ KB

In [ ]:
df['Runtime']=df['Runtime'].astype('int64')

In [ ]:
df.describe()

          Runtime  IMDB_Rating  Meta_score   No_of_Votes
count  714.000000   714.000000  714.000000  7.140000e+02
mean   123.715686     7.937115   77.158263  3.561348e+05
std     25.887535     0.293278   12.401144  3.539011e+05
min     72.000000     7.600000   28.000000  2.522900e+04
25%    104.250000     7.700000   70.000000  9.600975e+04
50%    120.000000     7.900000   78.000000  2.366025e+05
75%    136.000000     8.100000   86.000000  5.077922e+05
max    238.000000     9.300000  100.000000  2.343110e+06

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 997
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    714 non-null    object
 1   Series_Title   714 non-null    object
 2   Released_Year  714 non-null    object
 3   Certificate    714 non-null    object
 4   Runtime        714 non-null    int64
 5   Genre          714 non-null    object
 6   IMDB_Rating    714 non-null    float64
 7   Overview       714 non-null    object
 8   Meta_score     714 non-null    float64
 9   Director       714 non-null    object
 10  Star1          714 non-null    object
 11  Star2          714 non-null    object
 12  Star3          714 non-null    object
 13  Star4          714 non-null    object
 14  No_of_Votes    714 non-null    int64
 15  Gross          714 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 94.8+ KB

In [ ]:
filt1=(df['Runtime']>=180) & (df['IMDB_Rating']>=8)

In [ ]:
df[filt1]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
5,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,The Lord of the Rings: The Return of the King,2003,U,201,"Action, Adventure, Drama",8.9,Gandalf and Aragorn lead the World of Men agai...,94.0,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1642758,"377,845,905"
7,https://m.media-amazon.com/images/M/MV5BNDE4OT...,Schindler's List,1993,A,195,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",94.0,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,"96,898,818"
25,https://m.media-amazon.com/images/M/MV5BMTUxMz...,The Green Mile,1999,A,189,"Crime, Drama, Fantasy",8.6,The lives of guards on Death Row are affected ...,61.0,Frank Darabont,Tom Hanks,Michael Clarke Duncan,David Morse,Bonnie Hunt,1147794,"136,801,374"
31,https://m.media-amazon.com/images/M/MV5BOWE4ZD...,Shichinin no samurai,1954,U,207,"Action, Adventure, Drama",8.6,A poor village under attack by bandits recruit...,98.0,Akira Kurosawa,Toshirô Mifune,Takashi Shimura,Keiko Tsushima,Yukiko Shimazaki,315744,"269,061"
59,https://m.media-amazon.com/images/M/MV5BMTc5MD...,Avengers: Endgame,2019,UA,181,"Action, Adventure, Drama",8.4,After the devastating events of Avengers: Infi...,78.0,Anthony Russo,Joe Russo,Robert Downey Jr.,Chris Evans,Mark Ruffalo,809955,"858,373,000"
116,https://m.media-amazon.com/images/M/MV5BYWY5Zj...,Lawrence of Arabia,1962,U,228,"Adventure, Biography, Drama",8.3,"The story of T.E. Lawrence, the English office...",100.0,David Lean,Peter O'Toole,Alec Guinness,Anthony Quinn,Jack Hawkins,268085,"44,824,144"
147,https://m.media-amazon.com/images/M/MV5BMjIxMj...,The Wolf of Wall Street,2013,A,180,"Biography, Crime, Drama",8.2,"Based on the true story of Jordan Belfort, fro...",75.0,Martin Scorsese,Leonardo DiCaprio,Jonah Hill,Margot Robbie,Matthew McConaughey,1187498,"116,900,694"
247,https://m.media-amazon.com/images/M/MV5BNDYxNW...,Lagaan: Once Upon a Time in India,2001,U,224,"Adventure, Drama, Musical",8.1,The people of a small village in Victorian Ind...,84.0,Ashutosh Gowariker,Aamir Khan,Raghuvir Yadav,Gracy Singh,Rachel Shelley,105036,"70,147"
274,https://m.media-amazon.com/images/M/MV5BZmQzMD...,Fanny och Alexander,1982,A,188,Drama,8.1,Two young Swedish children experience the many...,100.0,Ingmar Bergman,Bertil Guve,Pernilla Allwin,Kristina Adolphson,Börje Ahlstedt,57784,"4,971,340"
278,https://m.media-amazon.com/images/M/MV5BNDhmNT...,The Deer Hunter,1978,A,183,"Drama, War",8.1,An in-depth examination of the ways in which t...,86.0,Michael Cimino,Robert De Niro,Christopher Walken,John Cazale,John Savage,311361,"48,979,328"
300,https://m.media-amazon.com/images/M/MV5BNjgxY2...,Ben-Hur,1959,U,212,"Adventure, Drama, History",8.1,After a Jewish prince is betrayed and sent int...,90.0,William Wyler,Charlton Heston,Jack Hawkins,Stephen Boyd,Haya Harareet,219466,"74,700,000"
314,https://m.media-amazon.com/images/M/MV5BYjUyZW...,Gone with the Wind,1939,U,238,"Drama, History, Romance",8.1,A manipulative woman and a roguish man conduct...,97.0,Victor Fleming,George Cukor,Sam Wood,Clark Gable,Vivien Leigh,290074,"198,676,459"
374,https://m.media-amazon.com/images/M/MV5BYmVjND...,Kal Ho Naa Ho,2003,U,186,"Comedy, Drama, Musical",8.0,"Naina, an introverted, perpetually depressed g...",54.0,Nikkhil Advani,Preity Zinta,Shah Rukh Khan,Saif Ali Khan,Jaya Bachchan,63460,"1,787,378"
383,https://m.media-amazon.com/images/M/MV5BZjk3YT...,Magnolia,1999,R,188,Drama,8.0,An epic mosaic of interrelated characters in s...,77.0,Paul Thomas Anderson,Tom Cruise,Jason Robards,Julianne Moore,Philip Seymour Hoffman,289742,"22,455,976"
397,https://m.media-amazon.com/images/M/MV5BNzZmMj...,Bound by Honor,1993,R,180,"Crime, Drama",8.0,Based on the true life experiences of poet Jim...,47.0,Taylor Hackford,Damian Chapa,Jesse Borrego,Benjamin Bratt,Enrique Castillo,28825,"4,496,583"
400,https://m.media-amazon.com/images/M/MV5BYjYyOD...,JFK,1991,UA,189,"Drama, History, Thriller",8.0,New Orleans District Attorney Jim Garrison dis...,72.0,Oliver Stone,Kevin Costner,Gary Oldman,Jack Lemmon,Walter Matthau,142110,"70,405,498"
402,https://m.media-amazon.com/images/M/MV5BMTY3OT...,Dances with Wolves,1990,U,181,"Adventure, Drama, Western",8.0,"Lieutenant John Dunbar, assigned to a remote w...",72.0,Kevin Costner,Kevin Costner,Mary McDonnell,Graham Greene,Rodney A. Grant,240266,"184,208,848"
411,https://m.media-amazon.com/images/M/MV5BMzJiZD...,Gandhi,1982,U,191,"Biography, Drama, History",8.0,The life of the lawyer who became the famed le...,79.0,Richard Attenborough,Ben Kingsley,John Gielgud,Rohini Hattangadi,Roshan Seth,217664,"52,767,889"
422,https://m.media-amazon.com/images/M/MV5BMWMxND...,Fiddler on the Roof,1971,G,181,"Drama, Family, Musical",8.0,"In prerevolutionary Russia, a Jewish peasant c...",67.0,Norman Jewison,Topol,Norma Crane,Leonard Frey,Molly Picon,39491,"80,500,000"
430,https://m.media-amazon.com/images/M/MV5BNzdmZT...,Doctor Zhivago,1965,A,197,"Drama, Romance, War",8.0,"The life of a Russian physician and poet who, ...",69.0,David Lean,Omar Sharif,Julie Christie,Geraldine Chaplin,Rod Steiger,69903,"111,722,000"

In [ ]:
filt1.value_counts()

False    693
True      21
dtype: int64

In [ ]:
len(df[filt1])

21